import { Movie } from '../types';

export const INITIAL_FEATURED_MOVIES: Movie[] = [
  {
    id: 'movie-the-last-hour-2024',
    title: 'The Last Hour',
    synopsis: 'A former operative is pulled back into a dangerous mission when his past comes knocking, confronting a conspiracy that reaches the highest levels of power.',
    genre: 'Action',
    secondary_genre: 'Thriller',
    release_year: 2024,
    duration_minutes: 124,
    rating: 4.9,
    review_count: 512,
    file_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
    thumbnail_url: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=700&auto=format&fit=crop&q=80',
    banner_url: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=1600&auto=format&fit=crop&q=80',
    download_permission: 'free',
    file_size_mb: 850,
    is_active: true,
    is_featured: true,
    director: 'Denis Villeneuve',
    vj_name: 'VJ Junior',
    cast: ['Alexander Ward', 'Elena Rostova', 'Marcus Sterling'],
    video_qualities: ['4K UHD', '1080p FHD', '720p HD'],
    audio_tracks: ['Dolby Atmos 7.1', 'English Stereo', 'Luganda [VJ Translation]'],
    subtitles: ['English', 'Spanish', 'French'],
    created_at: '2026-03-15T10:00:00Z',
  },
  {
    id: 'movie-broken-dreams-2023',
    title: 'Broken Dreams',
    synopsis: 'In a sprawling metropolis glowing with neon and shadows, an ambitious artist and a resilient undercover detective cross paths during the investigation of a high-society scandal.',
    genre: 'Drama',
    secondary_genre: 'Crime',
    release_year: 2023,
    duration_minutes: 118,
    rating: 4.8,
    review_count: 320,
    file_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    thumbnail_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=700&auto=format&fit=crop&q=80',
    banner_url: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=1600&auto=format&fit=crop&q=80',
    download_permission: 'free',
    file_size_mb: 790,
    is_active: true,
    is_featured: false,
    director: 'Chloe Zhao',
    vj_name: 'VJ Mark',
    cast: ['Sarah Jenkins', 'Amina Diallo', 'Liam Vance'],
    video_qualities: ['4K UHD', '1080p FHD'],
    audio_tracks: ['5.1 Surround', 'English Stereo', 'Luganda [VJ Translation]'],
    subtitles: ['English', 'French'],
    created_at: '2026-03-10T14:00:00Z',
  },
  {
    id: 'movie-city-shadows-2023',
    title: 'City Shadows',
    synopsis: 'A dedicated team of city detectives uncovers a sprawling underground network threatening the fabric of their home district.',
    genre: 'Action',
    secondary_genre: 'Crime',
    release_year: 2023,
    duration_minutes: 132,
    rating: 4.7,
    review_count: 285,
    file_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    thumbnail_url: 'https://images.unsplash.com/photo-1506703719100-a0f3a48c0f86?w=700&auto=format&fit=crop&q=80',
    banner_url: 'https://images.unsplash.com/photo-1506703719100-a0f3a48c0f86?w=1600&auto=format&fit=crop&q=80',
    download_permission: 'free',
    file_size_mb: 910,
    is_active: true,
    is_featured: false,
    director: 'Chad Stahelski',
    vj_name: 'VJ Junior',
    cast: ['Damian Vance', 'Chloe Zhang', 'Viktor Kray'],
    video_qualities: ['4K UHD', '1080p FHD'],
    audio_tracks: ['Dolby Atmos', 'English Stereo'],
    subtitles: ['English', 'German'],
    created_at: '2026-03-08T12:00:00Z',
  },
  {
    id: 'movie-the-journey-2022',
    title: 'The Journey',
    synopsis: 'A lone traveler undertakes an unforgettable odyssey across arid landscapes and forgotten civilizations to fulfill a promise made long ago.',
    genre: 'Adventure',
    secondary_genre: 'Drama',
    release_year: 2022,
    duration_minutes: 140,
    rating: 4.9,
    review_count: 440,
    file_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    thumbnail_url: 'https://images.unsplash.com/photo-1470246973918-29a93221c455?w=700&auto=format&fit=crop&q=80',
    banner_url: 'https://images.unsplash.com/photo-1470246973918-29a93221c455?w=1600&auto=format&fit=crop&q=80',
    download_permission: 'free',
    file_size_mb: 880,
    is_active: true,
    is_featured: false,
    director: 'Christopher Nolan',
    vj_name: 'VJ Ice P',
    cast: ['Michael Evans', 'Tara Okonkwo'],
    video_qualities: ['4K UHD', '1080p FHD'],
    audio_tracks: ['5.1 Surround', 'Luganda [VJ Translation]'],
    subtitles: ['English', 'Spanish'],
    created_at: '2026-03-05T09:00:00Z',
  },
  {
    id: 'movie-the-whisper-2024',
    title: 'The Whisper',
    synopsis: 'Deep in a rain-drenched coastal town, a secluded audio archivist intercepts an enigmatic signal broadcasting voices from events that have yet to occur.',
    genre: 'Horror',
    secondary_genre: 'Thriller',
    release_year: 2024,
    duration_minutes: 106,
    rating: 4.6,
    review_count: 198,
    file_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
    thumbnail_url: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=700&auto=format&fit=crop&q=80',
    banner_url: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=1600&auto=format&fit=crop&q=80',
    download_permission: 'free',
    file_size_mb: 680,
    is_active: true,
    is_featured: false,
    director: 'Guillermo del Toro',
    vj_name: 'VJ Emmy',
    cast: ['Klara Lind', 'Harlan Ross'],
    video_qualities: ['1080p FHD'],
    audio_tracks: ['Stereo', 'Luganda [VJ Translation]'],
    subtitles: ['English'],
    created_at: '2026-03-18T16:00:00Z',
  },
  {
    id: 'movie-the-escape-2024',
    title: 'The Escape',
    synopsis: 'Three strangers with interconnected secrets must orchestrate an impossible breakout across a heavily guarded military perimeter.',
    genre: 'Action',
    secondary_genre: 'Thriller',
    release_year: 2024,
    duration_minutes: 116,
    rating: 4.7,
    review_count: 310,
    file_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
    thumbnail_url: 'https://images.unsplash.com/photo-1511919884226-fd3cad34687c?w=700&auto=format&fit=crop&q=80',
    banner_url: 'https://images.unsplash.com/photo-1511919884226-fd3cad34687c?w=1600&auto=format&fit=crop&q=80',
    download_permission: 'free',
    file_size_mb: 740,
    is_active: true,
    is_featured: false,
    director: 'Justin Lin',
    vj_name: 'VJ Junior',
    cast: ['Marcus Cole', 'Naomi Reid', 'David Kim'],
    video_qualities: ['4K UHD', '1080p FHD'],
    audio_tracks: ['5.1 Surround', 'Luganda [VJ Translation]'],
    subtitles: ['English', 'French'],
    created_at: '2026-03-17T11:00:00Z',
  },
  {
    id: 'movie-shadow-line-2024',
    title: 'Shadow Line',
    synopsis: 'In an alternate 1980s retro-future, a private investigator navigates the neon alleys of a high-tech border zone to uncover a missing scientist.',
    genre: 'Sci-Fi',
    secondary_genre: 'Action',
    release_year: 2024,
    duration_minutes: 122,
    rating: 4.8,
    review_count: 245,
    file_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
    thumbnail_url: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=700&auto=format&fit=crop&q=80',
    banner_url: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=1600&auto=format&fit=crop&q=80',
    download_permission: 'free',
    file_size_mb: 820,
    is_active: true,
    is_featured: false,
    director: 'Ridley Scott',
    vj_name: 'VJ Mark',
    cast: ['Julian Cross', 'Sonia Petrova'],
    video_qualities: ['4K UHD', '1080p FHD'],
    audio_tracks: ['Dolby Atmos', 'English Stereo'],
    subtitles: ['English', 'German'],
    created_at: '2026-03-16T15:30:00Z',
  },
  {
    id: 'movie-higher-ground-2023',
    title: 'Higher Ground',
    synopsis: 'A mountainous rescue team embarks on a perilous high-altitude expedition when an emergency beacon goes off during the worst blizzard in decades.',
    genre: 'Adventure',
    secondary_genre: 'Drama',
    release_year: 2023,
    duration_minutes: 128,
    rating: 4.8,
    review_count: 260,
    file_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    thumbnail_url: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=700&auto=format&fit=crop&q=80',
    banner_url: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=1600&auto=format&fit=crop&q=80',
    download_permission: 'free',
    file_size_mb: 890,
    is_active: true,
    is_featured: false,
    director: 'Baltasar Kormakur',
    vj_name: 'VJ Ice P',
    cast: ['Erik Thorvald', 'Maya Jensen'],
    video_qualities: ['4K UHD', '1080p FHD'],
    audio_tracks: ['5.1 Surround', 'Luganda [VJ Translation]'],
    subtitles: ['English', 'Spanish'],
    created_at: '2026-03-14T08:00:00Z',
  },
];
