import { Movie } from '../types';

export const INITIAL_FEATURED_MOVIES: Movie[] = [
  {
    id: 'movie-the-last-frontier-2026',
    title: 'THE LAST FRONTIER',
    synopsis: 'In 2026, humanity’s deepest planetary survey vessel detects an anomalous orbital architecture at the edge of the known solar system, unlocking secrets that reshape our understanding of space and time.',
    genre: 'Sci-Fi',
    secondary_genre: 'Adventure',
    release_year: 2026,
    duration_minutes: 128,
    rating: 4.8,
    review_count: 342,
    file_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
    thumbnail_url: 'https://images.unsplash.com/photo-1506703719100-a0f3a48c0f86?w=600&auto=format&fit=crop&q=80',
    banner_url: 'https://images.unsplash.com/photo-1506703719100-a0f3a48c0f86?w=1600&auto=format&fit=crop&q=80',
    download_permission: 'free',
    file_size_mb: 850,
    is_active: true,
    is_featured: true,
    director: 'Denis Villeneuve',
    cast: ['Alexander Ward', 'Elena Rostova', 'Marcus Sterling'],
    video_qualities: ['4K UHD', '1080p FHD', '720p HD'],
    audio_tracks: ['Dolby Atmos 7.1', 'English Stereo'],
    subtitles: ['English', 'Spanish', 'French'],
    created_at: '2026-01-15T10:00:00Z',
  },
  {
    id: 'movie-shadow-protocol-2026',
    title: 'SHADOW PROTOCOL',
    synopsis: 'A clandestine black-ops operative discovers that the cybernetic syndicate he was deployed to neutralize is operating from within his own agency.',
    genre: 'Action',
    secondary_genre: 'Thriller',
    release_year: 2025,
    duration_minutes: 114,
    rating: 4.7,
    review_count: 218,
    file_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    thumbnail_url: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=600&auto=format&fit=crop&q=80',
    banner_url: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=1600&auto=format&fit=crop&q=80',
    download_permission: 'free',
    file_size_mb: 780,
    is_active: true,
    is_featured: false,
    director: 'Chad Stahelski',
    cast: ['Damian Vance', 'Chloe Zhang', 'Viktor Kray'],
    video_qualities: ['4K UHD', '1080p FHD'],
    audio_tracks: ['5.1 Surround', 'English Stereo'],
    subtitles: ['English', 'French'],
    created_at: '2026-02-10T14:00:00Z',
  },
  {
    id: 'movie-beyond-earth-2026',
    title: 'BEYOND EARTH',
    synopsis: 'After interstellar travel becomes viable, the pioneer expedition of the USS Horizon discovers an alien biosphere with inexplicable quantum entanglement signals.',
    genre: 'Sci-Fi',
    secondary_genre: 'Drama',
    release_year: 2026,
    duration_minutes: 135,
    rating: 4.9,
    review_count: 405,
    file_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    thumbnail_url: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=600&auto=format&fit=crop&q=80',
    banner_url: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=1600&auto=format&fit=crop&q=80',
    download_permission: 'free',
    file_size_mb: 920,
    is_active: true,
    is_featured: false,
    director: 'Christopher Nolan',
    cast: ['Sarah Jenkins', 'Tariq Al-Mansoor', 'Claire Dupont'],
    video_qualities: ['4K UHD', '1080p FHD'],
    audio_tracks: ['Dolby Atmos', 'English Stereo'],
    subtitles: ['English', 'German', 'Spanish'],
    created_at: '2026-03-01T12:00:00Z',
  },
  {
    id: 'movie-the-silent-hour-2026',
    title: 'THE SILENT HOUR',
    synopsis: 'A hearing-impaired detective in a remote industrial enclave becomes the sole witness to a high-profile syndicate homicide that corrupt forces will do anything to suppress.',
    genre: 'Thriller',
    secondary_genre: 'Crime',
    release_year: 2025,
    duration_minutes: 108,
    rating: 4.6,
    review_count: 189,
    file_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    thumbnail_url: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=600&auto=format&fit=crop&q=80',
    banner_url: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=1600&auto=format&fit=crop&q=80',
    download_permission: 'free',
    file_size_mb: 690,
    is_active: true,
    is_featured: false,
    director: 'David Fincher',
    cast: ['Maya Lin', 'Robert Callahan', 'Genevieve Moreau'],
    video_qualities: ['1080p FHD', '720p HD'],
    audio_tracks: ['5.1 Surround', 'English Stereo'],
    subtitles: ['English Closed Captions', 'Spanish'],
    created_at: '2026-02-20T09:00:00Z',
  },
  {
    id: 'movie-redemption-road-2026',
    title: 'REDEMPTION ROAD',
    synopsis: 'A former champion driver returns for one high-stakes cross-country run to protect his estranged family from an inescapable debt.',
    genre: 'Action',
    secondary_genre: 'Drama',
    release_year: 2024,
    duration_minutes: 112,
    rating: 4.5,
    review_count: 145,
    file_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
    thumbnail_url: 'https://images.unsplash.com/photo-1511919884226-fd3cad34687c?w=600&auto=format&fit=crop&q=80',
    banner_url: 'https://images.unsplash.com/photo-1511919884226-fd3cad34687c?w=1600&auto=format&fit=crop&q=80',
    download_permission: 'free',
    file_size_mb: 720,
    is_active: true,
    is_featured: false,
    director: 'Justin Lin',
    cast: ['Leo Cruz', 'Samantha Hayes'],
    video_qualities: ['1080p FHD'],
    audio_tracks: ['5.1 Surround'],
    subtitles: ['English'],
    created_at: '2026-01-05T15:00:00Z',
  },
  {
    id: 'movie-eternal-echoes-2026',
    title: 'ETERNAL ECHOES',
    synopsis: 'A heartfelt romantic drama tracing two lovers separated by continent and time, reunited by an unmailed series of handwritten letters.',
    genre: 'Drama',
    secondary_genre: 'Romance',
    release_year: 2025,
    duration_minutes: 120,
    rating: 4.7,
    review_count: 270,
    file_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
    thumbnail_url: 'https://images.unsplash.com/photo-1518199266791-5375a83190b7?w=600&auto=format&fit=crop&q=80',
    banner_url: 'https://images.unsplash.com/photo-1518199266791-5375a83190b7?w=1600&auto=format&fit=crop&q=80',
    download_permission: 'free',
    file_size_mb: 810,
    is_active: true,
    is_featured: false,
    director: 'Celine Song',
    cast: ['Marcus Bennett', 'Amina Diallo'],
    video_qualities: ['4K UHD', '1080p FHD'],
    audio_tracks: ['Stereo', 'Dolby 5.1'],
    subtitles: ['English', 'French'],
    created_at: '2026-02-14T08:00:00Z',
  }
];
